[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy>=1.22.4",
    "pandas>=1.4.2",
    "matplotlib>=3.3.4",
    "scipy>=1.8.1",
    "mapply>=0.1.7",
    "psutil>=5.8.0",
    "joblib>=1.0.1",
    "tqdm>=4.61.1",
]
build-backend = "setuptools.build_meta"